services:

  postgres:

    image: ${POSTGRES_IMAGE}

    container_name: ${POSTGRES_CONTAINER_NAME}

    hostname: ${POSTGRES_HOSTNAME}

    restart: unless-stopped

    ports:
      - "${POSTGRES_PORT}:5432"

    environment:

      POSTGRES_DB: ${POSTGRES_DB}

      POSTGRES_USER: ${POSTGRES_USER}

      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


    volumes:

      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data


    healthcheck:

      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]

      interval: 10s

      timeout: 5s

      retries: 5

      start_period: 15s


    networks:

      - orion-network



  redis:

    image: ${REDIS_IMAGE}

    container_name: ${REDIS_CONTAINER_NAME}

    hostname: ${REDIS_HOSTNAME}

    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:

      - ${REDIS_DATA_PATH}:/data


    healthcheck:

      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 10s

      timeout: 5s

      retries: 5

      start_period: 10s


    networks:

      - orion-network
networks:

  orion-network:

    name: orion-network

    external: true
